package com.nexus.tenant.infrastructure.persistence;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.UUID;

/**
 * Spring Data JPA repository for {@link TenantEntity}.
 *
 * <p>Provides standard CRUD operations: {@code save}, {@code findById},
 * {@code findAll}, {@code deleteById}, etc. — all auto-generated by
 * Spring Data at startup from the interface definition alone.
 *
 * <p>The {@code tenants} table does NOT have RLS enabled (the tenant ID
 * IS the row — there's nothing to filter by). This repository is used
 * mainly for validating that a tenant exists before creating tickets.
 */
@Repository
public interface TenantRepository extends JpaRepository<TenantEntity, UUID> {

    /**
     * Check if a tenant exists without loading the full entity.
     * More efficient than {@code findById().isPresent()} because it
     * generates {@code SELECT 1 WHERE id = ?} instead of {@code SELECT *}.
     */
    boolean existsById(UUID id);
}
