apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    # Access mode - proxy (Server in the UI) or direct (Browser in the UI).
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
